[package]
name = "paperd"
version = "0.1.0"
authors = ["Kyle Wood <demonwav@gmail.com>"]
edition = "2018"
license = "LGPL-3.0-only"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
clap = "~2.33.0"
nix = "0.14.1"
signal-hook = "0.1.9"
regex = "1"
sys-info = "0.5.7"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
