[package]
name = "paperd-lib"
version = "1.1.0-snapshot"
authors = ["Kyle Wood <demonwav@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1

[dependencies]
nix = "0.17.0"
